#!/bin/bash
#
# Perform necessary ronin setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

exit 0
